version: '3.4'
services:
  postgres-db:
    image: postgres:13-alpine
    platform: linux/x86_64
    environment:
      POSTGRES_PASSWORD: "wewillrockyou"
    ports:
      - 5432:5432
    networks:
      - app-network

networks:
  app-network:
    name: app-network
